USE retail_banking_dw;
GO

-- customer_key and account_key are surrogate keys generated by the warehouse.
-- Source IDs remain available as business identifiers.
IF OBJECT_ID(N'dw.dim_customer', N'U') IS NULL
BEGIN
    CREATE TABLE dw.dim_customer (
        customer_key INT IDENTITY(1,1) PRIMARY KEY,
        customer_id NVARCHAR(50) NOT NULL,
        customer_name NVARCHAR(100),
        city NVARCHAR(100),
        registration_date DATE
    );
END;

IF OBJECT_ID(N'dw.dim_account', N'U') IS NULL
BEGIN
    CREATE TABLE dw.dim_account (
        account_key INT IDENTITY(1,1) PRIMARY KEY,
        account_id NVARCHAR(50) NOT NULL UNIQUE,
        customer_key INT NULL,
        account_type NVARCHAR(50),
        opening_date DATE,
        status NVARCHAR(20),
        CONSTRAINT FK_dim_account_customer
            FOREIGN KEY (customer_key) REFERENCES dw.dim_customer(customer_key)
    );
END;
GO
